Repository IN-CORE/incore-docs, pull requests merged in 2022-02, with the labels that each got.

#68 67 update GitHub action to build jupyter book
  .github/workflows/ci.yaml
  manual_jb/Dockerfile
  manual_jb/content/_config.yml
Labels: enhancement

#72 fixed galvaston dfr3 view in notebook
  manual/source/notebooks/Galveston_testbed/Galveston_testbed.ipynb
  manual_jb/content/notebooks/Galveston_testbed/Galveston_testbed.ipynb
  notebooks/Galveston_testbed.zip
Labels: bug

#73 update and fix JB manual
  manual_jb/Dockerfile
  manual_jb/content/_toc.yml
  manual_jb/content/analyses.md
  manual_jb/content/analyses/pipeline_restoration.md
  manual_jb/content/notebooks.md
  manual_jb/content/notebooks_other.md
  manual_jb/content/workshops/20210526/agenda.md
  notebooks/pipeline_restoration.ipynb
Labels: bug, documentation, enhancement
